name: unzip hugo pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Unzip hugo pages
        run: 7z x publicExport.zip -ocontent -Y

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: unzip
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
