name: unzip hugo pages

on:
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Rebase Pulls
        uses: peter-evans/rebase@v2.0.1

      - name: Unzip hugo pages
        run: 7z x content/publicExport.zip -ocontent -Y

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          new_branch: unzipped-hugo
          push: true
