on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Logseq to Hugo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - run: npm install
        shell: bash
      - uses: atfornes/logseq-hugo-action@v1.3
